// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Temperature.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Temperature.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define Temperature_max_cdr_typesize 264ULL;
#define Temperature_max_key_cdr_typesize 0ULL;

Temperature::Temperature()
{
    // long m_temperature
    m_temperature = 0;
    // string m_timestamp
    m_timestamp ="";

}

Temperature::~Temperature()
{


}

Temperature::Temperature(
        const Temperature& x)
{
    m_temperature = x.m_temperature;
    m_timestamp = x.m_timestamp;
}

Temperature::Temperature(
        Temperature&& x) noexcept 
{
    m_temperature = x.m_temperature;
    m_timestamp = std::move(x.m_timestamp);
}

Temperature& Temperature::operator =(
        const Temperature& x)
{

    m_temperature = x.m_temperature;
    m_timestamp = x.m_timestamp;

    return *this;
}

Temperature& Temperature::operator =(
        Temperature&& x) noexcept
{

    m_temperature = x.m_temperature;
    m_timestamp = std::move(x.m_timestamp);

    return *this;
}

bool Temperature::operator ==(
        const Temperature& x) const
{

    return (m_temperature == x.m_temperature && m_timestamp == x.m_timestamp);
}

bool Temperature::operator !=(
        const Temperature& x) const
{
    return !(*this == x);
}

size_t Temperature::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Temperature_max_cdr_typesize;
}

size_t Temperature::getCdrSerializedSize(
        const Temperature& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.timestamp().size() + 1;


    return current_alignment - initial_alignment;
}

void Temperature::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_temperature;
    scdr << m_timestamp.c_str();

}

void Temperature::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_temperature;
    dcdr >> m_timestamp;
}

/*!
 * @brief This function sets a value in member temperature
 * @param _temperature New value for member temperature
 */
void Temperature::temperature(
        int32_t _temperature)
{
    m_temperature = _temperature;
}

/*!
 * @brief This function returns the value of member temperature
 * @return Value of member temperature
 */
int32_t Temperature::temperature() const
{
    return m_temperature;
}

/*!
 * @brief This function returns a reference to member temperature
 * @return Reference to member temperature
 */
int32_t& Temperature::temperature()
{
    return m_temperature;
}

/*!
 * @brief This function copies the value in member timestamp
 * @param _timestamp New value to be copied in member timestamp
 */
void Temperature::timestamp(
        const std::string& _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function moves the value in member timestamp
 * @param _timestamp New value to be moved in member timestamp
 */
void Temperature::timestamp(
        std::string&& _timestamp)
{
    m_timestamp = std::move(_timestamp);
}

/*!
 * @brief This function returns a constant reference to member timestamp
 * @return Constant reference to member timestamp
 */
const std::string& Temperature::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
std::string& Temperature::timestamp()
{
    return m_timestamp;
}


size_t Temperature::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Temperature_max_key_cdr_typesize;
}

bool Temperature::isKeyDefined()
{
    return false;
}

void Temperature::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

