// https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html

struct Image
{
	sequence<octet> image;
	string timestamp;
	unsigned long frame_number;
	unsigned long height;
	unsigned long width;

	unsigned long long t1;
	unsigned long long t2;
	unsigned long long t3;

	long frequency;
};
