// https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html

struct Image
{
	sequence<octet> image;
	unsigned long frame_number;
	unsigned long height;
	unsigned long width;

	unsigned long long subscriber_initalize_time;
	unsigned long long subscriber_send_time;
	unsigned long long publisher_recieve_time;
};
