// https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html

struct Temperature
{
	unsigned long index;
	long temperature;

	unsigned long long t1;
	unsigned long long t2;
	unsigned long long t3;

	long frequency;
};