// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Image.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Image.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define Image_max_cdr_typesize 400ULL;
#define Image_max_key_cdr_typesize 0ULL;

Image::Image()
{
    // sequence<octet> m_image

    // string m_timestamp
    m_timestamp ="";
    // unsigned long m_frame_number
    m_frame_number = 0;
    // unsigned long m_height
    m_height = 0;
    // unsigned long m_width
    m_width = 0;
    // long long m_t1
    m_t1 = 0;
    // long long m_t2
    m_t2 = 0;
    // long long m_t3
    m_t3 = 0;

}

Image::~Image()
{








}

Image::Image(
        const Image& x)
{
    m_image = x.m_image;
    m_timestamp = x.m_timestamp;
    m_frame_number = x.m_frame_number;
    m_height = x.m_height;
    m_width = x.m_width;
    m_t1 = x.m_t1;
    m_t2 = x.m_t2;
    m_t3 = x.m_t3;
}

Image::Image(
        Image&& x) noexcept 
{
    m_image = std::move(x.m_image);
    m_timestamp = std::move(x.m_timestamp);
    m_frame_number = x.m_frame_number;
    m_height = x.m_height;
    m_width = x.m_width;
    m_t1 = x.m_t1;
    m_t2 = x.m_t2;
    m_t3 = x.m_t3;
}

Image& Image::operator =(
        const Image& x)
{

    m_image = x.m_image;
    m_timestamp = x.m_timestamp;
    m_frame_number = x.m_frame_number;
    m_height = x.m_height;
    m_width = x.m_width;
    m_t1 = x.m_t1;
    m_t2 = x.m_t2;
    m_t3 = x.m_t3;

    return *this;
}

Image& Image::operator =(
        Image&& x) noexcept
{

    m_image = std::move(x.m_image);
    m_timestamp = std::move(x.m_timestamp);
    m_frame_number = x.m_frame_number;
    m_height = x.m_height;
    m_width = x.m_width;
    m_t1 = x.m_t1;
    m_t2 = x.m_t2;
    m_t3 = x.m_t3;

    return *this;
}

bool Image::operator ==(
        const Image& x) const
{

    return (m_image == x.m_image && m_timestamp == x.m_timestamp && m_frame_number == x.m_frame_number && m_height == x.m_height && m_width == x.m_width && m_t1 == x.m_t1 && m_t2 == x.m_t2 && m_t3 == x.m_t3);
}

bool Image::operator !=(
        const Image& x) const
{
    return !(*this == x);
}

size_t Image::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Image_max_cdr_typesize;
}

size_t Image::getCdrSerializedSize(
        const Image& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.image().size() > 0)
    {
        current_alignment += (data.image().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.timestamp().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void Image::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_image;
    scdr << m_timestamp.c_str();
    scdr << m_frame_number;
    scdr << m_height;
    scdr << m_width;
    scdr << m_t1;
    scdr << m_t2;
    scdr << m_t3;

}

void Image::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_image;
    dcdr >> m_timestamp;
    dcdr >> m_frame_number;
    dcdr >> m_height;
    dcdr >> m_width;
    dcdr >> m_t1;
    dcdr >> m_t2;
    dcdr >> m_t3;
}

/*!
 * @brief This function copies the value in member image
 * @param _image New value to be copied in member image
 */
void Image::image(
        const std::vector<uint8_t>& _image)
{
    m_image = _image;
}

/*!
 * @brief This function moves the value in member image
 * @param _image New value to be moved in member image
 */
void Image::image(
        std::vector<uint8_t>&& _image)
{
    m_image = std::move(_image);
}

/*!
 * @brief This function returns a constant reference to member image
 * @return Constant reference to member image
 */
const std::vector<uint8_t>& Image::image() const
{
    return m_image;
}

/*!
 * @brief This function returns a reference to member image
 * @return Reference to member image
 */
std::vector<uint8_t>& Image::image()
{
    return m_image;
}
/*!
 * @brief This function copies the value in member timestamp
 * @param _timestamp New value to be copied in member timestamp
 */
void Image::timestamp(
        const std::string& _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function moves the value in member timestamp
 * @param _timestamp New value to be moved in member timestamp
 */
void Image::timestamp(
        std::string&& _timestamp)
{
    m_timestamp = std::move(_timestamp);
}

/*!
 * @brief This function returns a constant reference to member timestamp
 * @return Constant reference to member timestamp
 */
const std::string& Image::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
std::string& Image::timestamp()
{
    return m_timestamp;
}
/*!
 * @brief This function sets a value in member frame_number
 * @param _frame_number New value for member frame_number
 */
void Image::frame_number(
        uint32_t _frame_number)
{
    m_frame_number = _frame_number;
}

/*!
 * @brief This function returns the value of member frame_number
 * @return Value of member frame_number
 */
uint32_t Image::frame_number() const
{
    return m_frame_number;
}

/*!
 * @brief This function returns a reference to member frame_number
 * @return Reference to member frame_number
 */
uint32_t& Image::frame_number()
{
    return m_frame_number;
}

/*!
 * @brief This function sets a value in member height
 * @param _height New value for member height
 */
void Image::height(
        uint32_t _height)
{
    m_height = _height;
}

/*!
 * @brief This function returns the value of member height
 * @return Value of member height
 */
uint32_t Image::height() const
{
    return m_height;
}

/*!
 * @brief This function returns a reference to member height
 * @return Reference to member height
 */
uint32_t& Image::height()
{
    return m_height;
}

/*!
 * @brief This function sets a value in member width
 * @param _width New value for member width
 */
void Image::width(
        uint32_t _width)
{
    m_width = _width;
}

/*!
 * @brief This function returns the value of member width
 * @return Value of member width
 */
uint32_t Image::width() const
{
    return m_width;
}

/*!
 * @brief This function returns a reference to member width
 * @return Reference to member width
 */
uint32_t& Image::width()
{
    return m_width;
}

/*!
 * @brief This function sets a value in member t1
 * @param _t1 New value for member t1
 */
void Image::t1(
        int64_t _t1)
{
    m_t1 = _t1;
}

/*!
 * @brief This function returns the value of member t1
 * @return Value of member t1
 */
int64_t Image::t1() const
{
    return m_t1;
}

/*!
 * @brief This function returns a reference to member t1
 * @return Reference to member t1
 */
int64_t& Image::t1()
{
    return m_t1;
}

/*!
 * @brief This function sets a value in member t2
 * @param _t2 New value for member t2
 */
void Image::t2(
        int64_t _t2)
{
    m_t2 = _t2;
}

/*!
 * @brief This function returns the value of member t2
 * @return Value of member t2
 */
int64_t Image::t2() const
{
    return m_t2;
}

/*!
 * @brief This function returns a reference to member t2
 * @return Reference to member t2
 */
int64_t& Image::t2()
{
    return m_t2;
}

/*!
 * @brief This function sets a value in member t3
 * @param _t3 New value for member t3
 */
void Image::t3(
        int64_t _t3)
{
    m_t3 = _t3;
}

/*!
 * @brief This function returns the value of member t3
 * @return Value of member t3
 */
int64_t Image::t3() const
{
    return m_t3;
}

/*!
 * @brief This function returns a reference to member t3
 * @return Reference to member t3
 */
int64_t& Image::t3()
{
    return m_t3;
}



size_t Image::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Image_max_key_cdr_typesize;
}

bool Image::isKeyDefined()
{
    return false;
}

void Image::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

