// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Temperature.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Temperature.h"
#include "TemperatureTypeObject.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define Temperature_max_cdr_typesize 32ULL;
#define Temperature_max_key_cdr_typesize 0ULL;

Temperature::Temperature()
{
    // unsigned long m_index
    m_index = 0;
    // long m_temperature
    m_temperature = 0;
    // unsigned long long m_subscriber_initalize_time
    m_subscriber_initalize_time = 0;
    // unsigned long long m_publisher_send_time
    m_publisher_send_time = 0;
    // unsigned long long m_subscriber_recieve_time
    m_subscriber_recieve_time = 0;

    // Just to register all known types
    registerTemperatureTypes();
}

Temperature::~Temperature()
{





}

Temperature::Temperature(
        const Temperature& x)
{
    m_index = x.m_index;
    m_temperature = x.m_temperature;
    m_subscriber_initalize_time = x.m_subscriber_initalize_time;
    m_publisher_send_time = x.m_publisher_send_time;
    m_subscriber_recieve_time = x.m_subscriber_recieve_time;
}

Temperature::Temperature(
        Temperature&& x) noexcept 
{
    m_index = x.m_index;
    m_temperature = x.m_temperature;
    m_subscriber_initalize_time = x.m_subscriber_initalize_time;
    m_publisher_send_time = x.m_publisher_send_time;
    m_subscriber_recieve_time = x.m_subscriber_recieve_time;
}

Temperature& Temperature::operator =(
        const Temperature& x)
{

    m_index = x.m_index;
    m_temperature = x.m_temperature;
    m_subscriber_initalize_time = x.m_subscriber_initalize_time;
    m_publisher_send_time = x.m_publisher_send_time;
    m_subscriber_recieve_time = x.m_subscriber_recieve_time;

    return *this;
}

Temperature& Temperature::operator =(
        Temperature&& x) noexcept
{

    m_index = x.m_index;
    m_temperature = x.m_temperature;
    m_subscriber_initalize_time = x.m_subscriber_initalize_time;
    m_publisher_send_time = x.m_publisher_send_time;
    m_subscriber_recieve_time = x.m_subscriber_recieve_time;

    return *this;
}

bool Temperature::operator ==(
        const Temperature& x) const
{

    return (m_index == x.m_index && m_temperature == x.m_temperature && m_subscriber_initalize_time == x.m_subscriber_initalize_time && m_publisher_send_time == x.m_publisher_send_time && m_subscriber_recieve_time == x.m_subscriber_recieve_time);
}

bool Temperature::operator !=(
        const Temperature& x) const
{
    return !(*this == x);
}

size_t Temperature::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Temperature_max_cdr_typesize;
}

size_t Temperature::getCdrSerializedSize(
        const Temperature& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void Temperature::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_index;
    scdr << m_temperature;
    scdr << m_subscriber_initalize_time;
    scdr << m_publisher_send_time;
    scdr << m_subscriber_recieve_time;

}

void Temperature::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_index;
    dcdr >> m_temperature;
    dcdr >> m_subscriber_initalize_time;
    dcdr >> m_publisher_send_time;
    dcdr >> m_subscriber_recieve_time;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Temperature::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t Temperature::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& Temperature::index()
{
    return m_index;
}

/*!
 * @brief This function sets a value in member temperature
 * @param _temperature New value for member temperature
 */
void Temperature::temperature(
        int32_t _temperature)
{
    m_temperature = _temperature;
}

/*!
 * @brief This function returns the value of member temperature
 * @return Value of member temperature
 */
int32_t Temperature::temperature() const
{
    return m_temperature;
}

/*!
 * @brief This function returns a reference to member temperature
 * @return Reference to member temperature
 */
int32_t& Temperature::temperature()
{
    return m_temperature;
}

/*!
 * @brief This function sets a value in member subscriber_initalize_time
 * @param _subscriber_initalize_time New value for member subscriber_initalize_time
 */
void Temperature::subscriber_initalize_time(
        uint64_t _subscriber_initalize_time)
{
    m_subscriber_initalize_time = _subscriber_initalize_time;
}

/*!
 * @brief This function returns the value of member subscriber_initalize_time
 * @return Value of member subscriber_initalize_time
 */
uint64_t Temperature::subscriber_initalize_time() const
{
    return m_subscriber_initalize_time;
}

/*!
 * @brief This function returns a reference to member subscriber_initalize_time
 * @return Reference to member subscriber_initalize_time
 */
uint64_t& Temperature::subscriber_initalize_time()
{
    return m_subscriber_initalize_time;
}

/*!
 * @brief This function sets a value in member publisher_send_time
 * @param _publisher_send_time New value for member publisher_send_time
 */
void Temperature::publisher_send_time(
        uint64_t _publisher_send_time)
{
    m_publisher_send_time = _publisher_send_time;
}

/*!
 * @brief This function returns the value of member publisher_send_time
 * @return Value of member publisher_send_time
 */
uint64_t Temperature::publisher_send_time() const
{
    return m_publisher_send_time;
}

/*!
 * @brief This function returns a reference to member publisher_send_time
 * @return Reference to member publisher_send_time
 */
uint64_t& Temperature::publisher_send_time()
{
    return m_publisher_send_time;
}

/*!
 * @brief This function sets a value in member subscriber_recieve_time
 * @param _subscriber_recieve_time New value for member subscriber_recieve_time
 */
void Temperature::subscriber_recieve_time(
        uint64_t _subscriber_recieve_time)
{
    m_subscriber_recieve_time = _subscriber_recieve_time;
}

/*!
 * @brief This function returns the value of member subscriber_recieve_time
 * @return Value of member subscriber_recieve_time
 */
uint64_t Temperature::subscriber_recieve_time() const
{
    return m_subscriber_recieve_time;
}

/*!
 * @brief This function returns a reference to member subscriber_recieve_time
 * @return Reference to member subscriber_recieve_time
 */
uint64_t& Temperature::subscriber_recieve_time()
{
    return m_subscriber_recieve_time;
}



size_t Temperature::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return Temperature_max_key_cdr_typesize;
}

bool Temperature::isKeyDefined()
{
    return false;
}

void Temperature::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}

