// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UpdateThermometerTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "UpdateThermometer.h"
#include "UpdateThermometerTypeObject.h"
#include <mutex>
#include <utility>
#include <sstream>
#include <fastdds/rtps/common/CdrSerialization.hpp>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>

using namespace eprosima::fastrtps::rtps;

void registerUpdateThermometerTypes()
{
    static std::once_flag once_flag;
    std::call_once(once_flag, []()
            {
                TypeObjectFactory *factory = TypeObjectFactory::get_instance();
                factory->add_type_object("UpdateThermometer", GetUpdateThermometerIdentifier(true),
                GetUpdateThermometerObject(true));
                factory->add_type_object("UpdateThermometer", GetUpdateThermometerIdentifier(false),
                GetUpdateThermometerObject(false));

            });
}



const TypeIdentifier* GetUpdateThermometerIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("UpdateThermometer", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetUpdateThermometerObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("UpdateThermometer", complete);
}

const TypeObject* GetUpdateThermometerObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("UpdateThermometer", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteUpdateThermometerObject();
    }
    //else
    return GetMinimalUpdateThermometerObject();
}

const TypeObject* GetMinimalUpdateThermometerObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("UpdateThermometer", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_subscriber_initalize_time;
    mst_subscriber_initalize_time.common().member_id(memberId++);
    mst_subscriber_initalize_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_subscriber_initalize_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_subscriber_initalize_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_subscriber_initalize_time.common().member_flags().IS_OPTIONAL(false);
    mst_subscriber_initalize_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_subscriber_initalize_time.common().member_flags().IS_KEY(false);
    mst_subscriber_initalize_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_subscriber_initalize_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    MD5 subscriber_initalize_time_hash("subscriber_initalize_time");
    for(int i = 0; i < 4; ++i)
    {
        mst_subscriber_initalize_time.detail().name_hash()[i] = subscriber_initalize_time_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_subscriber_initalize_time);

    MinimalStructMember mst_publisher_send_time;
    mst_publisher_send_time.common().member_id(memberId++);
    mst_publisher_send_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_publisher_send_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_publisher_send_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_publisher_send_time.common().member_flags().IS_OPTIONAL(false);
    mst_publisher_send_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_publisher_send_time.common().member_flags().IS_KEY(false);
    mst_publisher_send_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_publisher_send_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    MD5 publisher_send_time_hash("publisher_send_time");
    for(int i = 0; i < 4; ++i)
    {
        mst_publisher_send_time.detail().name_hash()[i] = publisher_send_time_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_publisher_send_time);

    MinimalStructMember mst_subscriber_recieve_time;
    mst_subscriber_recieve_time.common().member_id(memberId++);
    mst_subscriber_recieve_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_subscriber_recieve_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_subscriber_recieve_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_subscriber_recieve_time.common().member_flags().IS_OPTIONAL(false);
    mst_subscriber_recieve_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_subscriber_recieve_time.common().member_flags().IS_KEY(false);
    mst_subscriber_recieve_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_subscriber_recieve_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    MD5 subscriber_recieve_time_hash("subscriber_recieve_time");
    for(int i = 0; i < 4; ++i)
    {
        mst_subscriber_recieve_time.detail().name_hash()[i] = subscriber_recieve_time_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_subscriber_recieve_time);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];
    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    eprosima::fastcdr::CdrSizeCalculator calculator(eprosima::fastcdr::CdrVersion::XCDRv1);
    size_t current_alignment {0};
    SerializedPayload_t payload(static_cast<uint32_t>(
        calculator.calculate_serialized_size(type_object->minimal().struct_type(), current_alignment) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::CdrVersion::XCDRv1); // Object that serializes the data.
    payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

    ser << *type_object;
#if FASTCDR_VERSION_MAJOR == 1
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
#else
    payload.length = (uint32_t)ser.get_serialized_data_length(); //Get the serialized length
#endif // FASTCDR_VERSION_MAJOR == 1
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("UpdateThermometer", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("UpdateThermometer", false);
}

const TypeObject* GetCompleteUpdateThermometerObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("UpdateThermometer", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_subscriber_initalize_time;
    cst_subscriber_initalize_time.common().member_id(memberId++);
    cst_subscriber_initalize_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_subscriber_initalize_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_subscriber_initalize_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_subscriber_initalize_time.common().member_flags().IS_OPTIONAL(false);
    cst_subscriber_initalize_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_subscriber_initalize_time.common().member_flags().IS_KEY(false);
    cst_subscriber_initalize_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_subscriber_initalize_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    cst_subscriber_initalize_time.detail().name("subscriber_initalize_time");

    type_object->complete().struct_type().member_seq().emplace_back(cst_subscriber_initalize_time);

    CompleteStructMember cst_publisher_send_time;
    cst_publisher_send_time.common().member_id(memberId++);
    cst_publisher_send_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_publisher_send_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_publisher_send_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_publisher_send_time.common().member_flags().IS_OPTIONAL(false);
    cst_publisher_send_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_publisher_send_time.common().member_flags().IS_KEY(false);
    cst_publisher_send_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_publisher_send_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    cst_publisher_send_time.detail().name("publisher_send_time");

    type_object->complete().struct_type().member_seq().emplace_back(cst_publisher_send_time);

    CompleteStructMember cst_subscriber_recieve_time;
    cst_subscriber_recieve_time.common().member_id(memberId++);
    cst_subscriber_recieve_time.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_subscriber_recieve_time.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_subscriber_recieve_time.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_subscriber_recieve_time.common().member_flags().IS_OPTIONAL(false);
    cst_subscriber_recieve_time.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_subscriber_recieve_time.common().member_flags().IS_KEY(false);
    cst_subscriber_recieve_time.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_subscriber_recieve_time.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("uint64_t", false));


    cst_subscriber_recieve_time.detail().name("subscriber_recieve_time");

    type_object->complete().struct_type().member_seq().emplace_back(cst_subscriber_recieve_time);


    // Header
    type_object->complete().struct_type().header().detail().type_name("UpdateThermometer");
    // TODO inheritance
    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    eprosima::fastcdr::CdrSizeCalculator calculator(eprosima::fastcdr::CdrVersion::XCDRv1);
    size_t current_alignment {0};
    SerializedPayload_t payload(static_cast<uint32_t>(
        calculator.calculate_serialized_size(type_object->complete().struct_type(), current_alignment) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::CdrVersion::XCDRv1); // Object that serializes the data.
    payload.encapsulation = ser.endianness() == eprosima::fastcdr::Cdr::BIG_ENDIANNESS ? CDR_BE : CDR_LE;

    ser << *type_object;
#if FASTCDR_VERSION_MAJOR == 1
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
#else
    payload.length = (uint32_t)ser.get_serialized_data_length(); //Get the serialized length
#endif // FASTCDR_VERSION_MAJOR == 1
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("UpdateThermometer", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("UpdateThermometer", true);
}
